#include "translations/castellano/player_names.inc"
#include "translations/castellano/npcs.inc"
#include "translations/castellano/carteles_y_edificios.inc"
#include "translations/castellano/menus.inc"	;menús: batalla, tiendas, etc.
#include "translations/castellano/monstruos.inc"
#include "translations/castellano/batallas.inc"
#include "translations/castellano/items.inc"	;armas, elementos, armadura
