itemBread:
.db "Pan",0,"Es un poco seco...",0
itemDriedFruit:
.db "Frutos Secos",0,"Un poco de todo, con sal",0
itemPie:
.db "Empanadilla",0,"Es vegetariana",0
itemWarmWater:
.db "Agua Caliente",0,"Buena para la salud",0
itemTea:
.db "Te",0,"Calienta el alma",0
itemHerb:
.db "Hierba",0,"Puedes aplicarla sobre las heridas",0
itemMedicine:
.db "Medicina",0,"Para heridas más graves",0
itemFlower:
.db "Flor",0,"Al menos es muy bonita!",0
