npc0txt:
.db "Unos veinte murieron en la explosión de anoche, todos policías honestos, con familias. "
.db "Los terroristas dicen que nuestro gobierno es corrupto y siempre están hablando de su "
.db "libertad y toda esa vaina, pero en mi opinión no son más que unos bandidos malhechores "
.db "buscando pretextos para su delincuencia. Cómo puedes justificar el asesinato, y encima "
.db "el asesinato de gente inocente?",$FF

npc1txt:
.db "Ha oído usted de la explosión terrorista de anoche? Dicen que fue una retaliación de la Vesna por haber ejecutado a algunos de sus miembros. No entiendo por qué hay que derramar tanta sangre...",$FF

npc2txt:
.db "No los defiendo, los Vesna, pero el ataque de anoche tampoco me sorprende. Por una parte casi me alegro. La PODA tiene que darse cuenta de que no puede hacer lo que quiera.",$FF

ari_txt1:
.db "Ay! Qué hombre! Oístes? Lo consiguió, sí! Lo vamos hacer reventar to', ya verás. "
.db "Un mundo nuevo nacerá de esta miseria como una flor de la mierda. "
.db "La PODA ya nos tiene miedo, y con razón. Ah, pero... no he visto a Farber desde anoche, dónde estará?",$FF
