battleCharacterSprites:
#include "sprites/battle/characters/franci.bmp"
#include "sprites/battle/characters/franci_mask.bmp"
#include "sprites/battle/characters/anselmo.bmp"
#include "sprites/battle/characters/anselmo_mask.bmp"
#include "sprites/battle/characters/porter.bmp"
#include "sprites/battle/characters/porter_mask.bmp"

battleMenu:
#include "sprites/battle/battleMenu.bmp"
battleMenuMask:
#include "sprites/battle/battleMenu_mask.bmp"

attackBarLeft:
#include "sprites/battle/attackBar_left.bmp"
#include "sprites/battle/attackBar_left_mask.bmp"
attackBarRight:
#include "sprites/battle/attackBar_right.bmp"
#include "sprites/battle/attackBar_right_mask.bmp"

